version: '3'
services:
    bot:
        build: ./bot
        depends_on: 
            - db
    db:
        build: ./db
        ports:
            - 8080:8080
        volumes:
            - /usr/src/app/node_modules