version: '3'
services:
    bot:
        build: ./bot
        depends_on:
            - db
        environment:
          - AD_USERNAME=${AD_USERNAME:-mwest5078}
          - USE_PROXIES=${USE_PROXIES:-0}               # For enabling proxies
          - CHANGE_LOCATION=${CHANGE_LOCATION:-1}       # Spoofing location
          - LOAD_SESSION=${LOAD_SESSION:-1}             # Loading previous session data
        volumes:
            - ./out:/tmp/out
            - ./profiles:/home/bot/profiles
    db:
        build: ./db
        ports:
            - 8080:8080
        volumes:
            - /usr/src/app/node_modules
    dashboard:
        build: ./dashboard
        depends_on:
            - db
        ports:
            - 5000:5000
        environment:
          - DB_URI=${DB_URI:-http://db:8080}

volumes:
    profile:
