version: '3'
services:
    bot:
        build: ./bot
        depends_on:
            - db
        environment:
          - AD_USERNAME=${AD_USERNAME:-mwest5078}
          - NUM_TERMS=${NUM_TERMS:-2}
          - USE_PROXIES=${USE_PROXIES:-0}
          - CHANGE_LOCATION=${CHANGE_LOCATION:-0}
          - UPLOAD_LOGS=${UPLOAD_LOGS:-0}
          - DB_URL=${DB_URL:-http://db:8080}
        volumes:
            - ./bot/out:/app/out
    db:
        build: ./db
        ports:
            - 8080:8080
        volumes:
            - /usr/src/app/node_modules
    dashboard:
        build: ./dashboard
        depends_on:
            - db
        ports:
            - 5000:5000
        environment:
          - DB_URI=${DB_URI:-http://db:8080}
